### ISSUE TITLE
Android Crash In Version 4.1.3 (not present in 4.1.0)

### ISSUE THREAD

**Issue by T-T-P** [RadekVyM/SimpleToolkit#63]
Hi, firstly thank you for building and maintaining such a great toolkit, it's greatly appreciated 👍 

I just wanted to report a crash I receive in Android since upgrading to version 4.1.3 (downgrading back to 4.1.0 resolves the crash), below is the trace if that helps at all?

It doesn't occur immediately it seems to occur randomly upon switching pages?

> Attempt to invoke virtual method 'void android.view.animation.Animation.setStartTime(long)' on a null object reference
>    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)
>    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
>    at Android.Views.View.StartAnimation(Animation animation)
>    at SimpleToolkit.SimpleShell.NavigationManager.PlatformSimpleStackNavigationManager.NavigateWithPlatformTransitionToPageInContainer(SimpleShell shell, IView previousShellItemContainer, IView previousShellSectionContainer, IView previousPage, Boolean isPreviousPageRoot, Func`2 pageTransition, Func`1 args, Boolean animated)
>    at SimpleToolkit.SimpleShell.NavigationManager.PlatformSimpleStackNavigationManager.NavigateToPage(SimpleShellTransitionType transitionType, PresentationMode presentationMode, ArgsNavigationRequest args, SimpleShell shell, IReadOnlyList`1 newPageStack, IView previousShellItemContainer, IView previousShellSectionContainer, IView previousPage, Boolean isPreviousPageRoot)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
>    at Java.Lang.Thread.RunnableImplementor.Run()
>    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
>    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)

**Comment by andersonvieiragomeslopes** [comment]
Update: I tested it in my project and disabling the animation also solves the problem.


`UseSimpleShell(false);`
